# Generated by Django 6.0.4 on 2026-04-15 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactAffixList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactSuit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('equip_bracer', 'Flower of Life'), ('equip_necklace', 'Plume of Dusk'), ('equip_ring', 'Sands of Eon'), ('equip_shoes', 'Goblet of Eon'), ('equip_dress', 'Circlet of Logos')], max_length=20)),
                ('max_level', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_icon', models.ImageField(upload_to='images/characters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level_list', models.PositiveSmallIntegerField()),
                ('rarity', models.CharField(choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=1)),
                ('icon', models.ImageField(upload_to='images/artifacts')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affix_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshin.artifactaffixlist')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshin.artifactsuit')),
            ],
        ),
    ]
