# Generated by Django 6.0.4 on 2026-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
