# Generated by Django 6.0.4 on 2026-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='affix_list',
        ),
        migrations.AddField(
            model_name='artifact',
            name='affix_list',
            field=models.ManyToManyField(blank=True, related_name='artifacts', to='genshin.artifactaffixlist'),
        ),
    ]
