# Generated by Django 6.0.4 on 2026-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0002_artifact_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='level_list',
            field=models.JSONField(),
        ),
    ]
