# Generated by Django 6.0.4 on 2026-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0002_remove_artifact_affix_list_artifact_affix_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactsuit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='suit',
        ),
        migrations.AlterField(
            model_name='artifactsuit',
            name='max_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifactsuit',
            name='type',
            field=models.CharField(blank=True, choices=[('equip_bracer', 'Flower of Life'), ('equip_necklace', 'Plume of Dusk'), ('equip_ring', 'Sands of Eon'), ('equip_shoes', 'Goblet of Eon'), ('equip_dress', 'Circlet of Logos')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='suit',
            field=models.ManyToManyField(blank=True, related_name='artifacts', to='genshin.artifactsuit'),
        ),
    ]
