# Generated by Django 6.0.4 on 2026-04-15 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0003_alter_artifact_level_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='level_list',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshin.rarity'),
        ),
    ]
