# Generated by Django 6.0.4 on 2026-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0003_artifactsuit_description_remove_artifact_suit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactsuit',
            name='type',
            field=models.CharField(blank=True, choices=[('EQUIP_BRACER', 'Flower of Life'), ('EQUIP_NECKLACE', 'Plume of Dusk'), ('EQUIP_RING', 'Sands of Eon'), ('EQUIP_SHOES', 'Goblet of Eon'), ('EQUIP_DRESS', 'Circlet of Logos')], max_length=20, null=True),
        ),
    ]
