# Generated by Django 6.0.4 on 2026-04-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0004_alter_artifactsuit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactaffixlist',
            name='name',
            field=models.TextField(),
        ),
    ]
