# Generated by Django 6.0.4 on 2026-04-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0004_rarity_remove_artifact_level_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rarity',
            old_name='value',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='rarity',
        ),
        migrations.AddField(
            model_name='artifact',
            name='rarities',
            field=models.ManyToManyField(related_name='artifacts', to='genshin.rarity'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='affix_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genshin.artifactaffixlist'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/artifacts'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='suit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genshin.artifactsuit'),
        ),
    ]
