# Generated by Django 6.0.4 on 2026-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0005_alter_artifactaffixlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactsuit',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/artifacts/suits'),
        ),
    ]
