# Generated by Django 6.0.4 on 2026-04-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0005_rename_value_rarity_level_remove_artifact_rarity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rarity',
            options={'verbose_name_plural': 'Rarities'},
        ),
    ]
