# Generated by Django 6.0.4 on 2026-04-18 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0006_artifactsuit_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('type', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='artifact',
            old_name='source_id',
            new_name='external_id',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/materials')),
                ('description', models.TextField(blank=True, null=True)),
                ('rarities', models.ManyToManyField(related_name='materials', to='genshin.rarity')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='genshin.materialsource')),
            ],
        ),
    ]
