# Generated by Django 6.0.4 on 2026-04-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0007_materialsource_rename_source_id_artifact_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
