# Generated by Django 6.0.4 on 2026-04-18 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0008_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsource',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, null=True),
        ),
    ]
