# Generated by Django 6.0.4 on 2026-04-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0009_materialsource_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='source',
        ),
        migrations.AddField(
            model_name='materialsource',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='genshin.material'),
        ),
    ]
