# Generated by Django 6.0.4 on 2026-04-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0010_remove_material_source_materialsource_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsource',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialsource',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
