# Generated by Django 6.0.4 on 2026-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0011_alter_materialsource_name_alter_materialsource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='rarities',
        ),
        migrations.AddField(
            model_name='material',
            name='rarity',
            field=models.CharField(blank=True, choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=1, null=True),
        ),
    ]
