# Generated by Django 6.0.4 on 2026-04-19 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0012_remove_material_rarities_material_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='rarities',
        ),
        migrations.AddField(
            model_name='artifact',
            name='rarities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=1), blank=True, default=list, null=True),
        ),
    ]
