# Generated by Django 6.0.4 on 2026-04-19 11:37

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0013_remove_artifact_rarities_artifact_rarities'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponAffix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('refinement', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rarity', models.CharField(blank=True, choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=1, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/weapons')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affix_list', models.ManyToManyField(blank=True, null=True, related_name='weapons', to='genshin.weaponaffix')),
            ],
        ),
    ]
