# Generated by Django 6.0.4 on 2026-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0014_weaponaffix_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='affix_list',
            field=models.ManyToManyField(blank=True, related_name='weapons', to='genshin.weaponaffix'),
        ),
    ]
