# Generated by Django 5.2.8 on 2025-11-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='model_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
